name: Publish Docker
on:
  - push
  - schedule:
    - cron: "* 22 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
      - run: |
          curl -fSL "https://github.com/genuinetools/reg/releases/download/v0.16.1/reg-linux-amd64" -o "/usr/local/bin/reg"
          chmod a+x "/usr/local/bin/reg"
          pip install -r .github/workflows/requirements.txt
          python .github/workflows/repo-sync.py